```
name: WhatsApp Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          WHATSAPP_TOKEN: ${{ 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 }} 
          WHATSAPP_SESSION_ID: ${ 101TkYESVBDOsUwOv_A_N_Y_A_V_2_eSz}}
          WHATSAPP_PHONE_NUMBER: ${{ +27781673022}}

      - name: Build and start WhatsApp bot
        run: |
          npm run build
          npm run start

      - name: Keep WhatsApp bot running
        run: |
          while true
          do
            sleep 1
          done
